openapi: 3.0.0
info:
  title: Ecommerce API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000/api/v1/
    description: Local server description, e.g. Local server
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /category/list-category:
    get:
      tags: 
        - category
      summary: Returns a list of category.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of category
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /category/get-category/{categoryId}:
    get:
      tags: 
        - category
      summary: Returns a list of category.
      parameters:
        - name: categoryId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of category
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /category/create-category:
    post:
      tags: 
        - category
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id: 
                  type: number
                name:
                  type: string
                description:
                  type: string
                image:
                  type: string
      responses: 
        '201':
          description: Created

